pool:
  vmImage: 'windows-latest'

steps:
- script: dotnet publish /p:WebPublishMethod=Package
  displayName: 'Publish Package'
  workingDirectory: './terrafawesome'

- task: AzureRmWebAppDeployment@4
  displayName: 'Deploy to Azure'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'azure'
    appType: 'webApp'
    WebAppName: '$(WebAppName)'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'