pool:
  vmImage: 'windows-latest'

steps:
- script: dotnet publish /p:WebPublishMethod=Package
  displayName: 'dotnet publish /p:WebPublishMethod=Package'
  workingDirectory: './terrafawesome'


# - task: AzureWebApp@1
#   inputs:
#     azureSubscription: 'terrafawesome-nonprod'
#     appType: 'webApp'
#     appName: 'terrafawesome'
#     package: '$(System.DefaultWorkingDirectory)/**/*.zip'
#     deploymentMethod: 'auto'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'terrafawesome-nonprod'
    appType: 'webApp'
    WebAppName: 'terrafawesome'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'